# -*- coding: utf-8 -*-
"""dat to step final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N212xrDyJdhdHIielapyCE2T_fDEs2gC
"""

import cadquery as cq
from cadquery import exporters
from math import hypot
import os

filename = "naca0012.dat"

# -----------------------
# Read DAT
# -----------------------
pts = []

with open(filename) as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) != 2:
            continue
        try:
            x = float(parts[0])
            y = float(parts[1])
            pts.append((x,y))
        except:
            pass

print("Original points:", len(pts))

# -----------------------
# Remove duplicate points
# -----------------------

clean = []

tol = 1e-7

for p in pts:
    if not clean:
        clean.append(p)
    else:
        if hypot(p[0]-clean[-1][0], p[1]-clean[-1][1]) > tol:
            clean.append(p)

pts = clean

print("Clean points:", len(pts))

# Close profile
if pts[0] != pts[-1]:
    pts.append(pts[0])

# -----------------------
# Build wire
# -----------------------

wp = cq.Workplane("XY")

wp = wp.polyline(pts).close()

solid = wp.extrude(1.0)

out = os.path.splitext(filename)[0] + ".step"

exporters.export(solid,out)

print("Saved:",out)